source 'https://rubygems.org'
gem 'rails', '4.1.6'
gem 'pg'
gem 'jquery-ui-rails'
gem 'open_uri_redirections'
gem 'bootstrap-sass', '3.3.0.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',                    group: :development
gem 'bcrypt', '~> 3.1.7'
gem 'mechanize', '~> 2.6.0'
gem 'activejob_backport' 
gem 'nokogiri'
gem 'httparty'
gem 'pry'
